### ISSUE TITLE
User: Search Tickets 

### ISSUE THREAD

**Issue by ghost** [sa3664/Group3_TrainTicketingSystem#1]
Description : This describes the process to search for a train ticket.

Acceptance Criteria : When searching for a ticket , the traveler should be able to do as mentioned below-

a)	 The traveler chooses either one-way and round-trip, chooses a date, and clicks "enter". The system will display all the itineraries meeting given criteria.
b)	The traveler will have an option to search for trains on particular time of the day  and clicks "enter". The system will display all the itineraries meeting given criteria.
c)	The traveler will get an error alert message with no search results if the source and destination entered are same. 
d)	The traveler will have to mandatory fill in the source , destination and date of the travel details as part of validation in order to proceed for finding the trains.

**Comment by sa3664** [comment]
In Progress

**Comment by sa3664** [comment]
The Search functionality has been completed and the code has been uploaded.
