### ISSUE TITLE
User: Add to cart (with or without discount options)

### ISSUE THREAD

**Issue by priyatj** [sa3664/Group3_TrainTicketingSystem#10]
Description: Should describe the process to add the selected ticket to cart after the search and itinerary has been decided by the traveler.

Acceptance criteria:
a)	The traveler should be able to have an option to add the desired train into the cart and proceed with checkout.
b)	The traveler should be able to get an error alert if he tries to add the train/ticket to cart without selecting from the list of trains available.
c)	The traveler should be able to have an option to get the discount on basis of the category they choose such as adult , senior citizen , passenger with disability , rail passenger assoc. adult , Military adult.

**Comment by sa3664** [comment]
In Progress

**Comment by sa3664** [comment]
The issue has been completed as described.
