### ISSUE TITLE
User: Checkout

### ISSUE THREAD

**Issue by priyatj** [sa3664/Group3_TrainTicketingSystem#11]
Description: Should describe the process to proceed with checkout after the search and itinerary has been finalized by the traveler

Acceptance criteria:
a)	The traveler should be able to have to enter the details such as name , email address and phone without which they won’t be able to proceed further for checkout.
b)	The traveler should be able to have an option to add the protection plan if desired.
c)	The traveler should be able to get an option to pay via any credit/debit or gift card to have secure checkout.

**Comment by Jijogeorge69** [comment]
In Progress

**Comment by sa3664** [comment]
The issue is completed successfully.
